Repository thermondo/lets-learn-kotlin, pull requests merged in 2022-12, with the labels that each got.

#43 [Housekeeping] Basic Re-naming
  basics/src/main/kotlin/de/thermondo/basics/Basics01.kt
  basics/src/main/kotlin/de/thermondo/basics/Basics02.kt
  basics/src/main/kotlin/de/thermondo/basics/Basics03.kt
  basics/src/main/kotlin/de/thermondo/basics/Basics04.kt
  basics/src/test/kotlin/de/thermondo/basics/Basics01Test.kt
  basics/src/test/kotlin/de/thermondo/basics/Basics02Test.kt
  basics/src/test/kotlin/de/thermondo/basics/Basics03Test.kt
  basics/src/test/kotlin/de/thermondo/basics/Basics04Test.kt
  solutions/src/main/kotlin/de/thermondo/solutions/basics/Basics01Solution.kt
  solutions/src/main/kotlin/de/thermondo/solutions/basics/Basics02Solution.kt
  solutions/src/main/kotlin/de/thermondo/solutions/basics/Basics03Solution.kt
  solutions/src/main/kotlin/de/thermondo/solutions/basics/Basics04Solution.kt
  solutions/src/test/kotlin/de/thermondo/solutions/basics/Basics01SolutionTest.kt
  solutions/src/test/kotlin/de/thermondo/solutions/basics/Basics02SolutionTest.kt
  solutions/src/test/kotlin/de/thermondo/solutions/basics/Basics03SolutionTest.kt
  solutions/src/test/kotlin/de/thermondo/solutions/basics/Basics04SolutionTest.kt
Labels: housekeeping :broom:

#10 [Basic] Task 5 Creating Classes
  basics/src/main/kotlin/de/thermondo/basics/Basics05.kt
  basics/src/test/kotlin/de/thermondo/basics/Basics5Test.kt
  solutions/src/main/kotlin/de/thermondo/solutions/basics/Basics05Solution.kt
  solutions/src/test/kotlin/de/thermondo/solutions/basics/Basics05SolutionTest.kt
Labels: basics :baby:

#46 [Fix] Revert Java Action Back to Version 3.6.0
  .github/workflows/main.yml
Labels: bug

#21 [Basic] Task 6 Passing Parameters to Class Constructors
  basics/src/main/kotlin/de/thermondo/basics/Basics06.kt
  basics/src/test/kotlin/de/thermondo/basics/Basics06Test.kt
  solutions/src/main/kotlin/de/thermondo/solutions/basics/Basics06Solution.kt
  solutions/src/test/kotlin/de/thermondo/solutions/basics/Basics06SolutionTest.kt
Labels: basics :baby:

#44 [Fix] Basic05Test Naming
  basics/src/test/kotlin/de/thermondo/basics/Basics05Test.kt
Labels: housekeeping :broom:
